### ISSUE TITLE
DBPedia2016-10 does not work

### ISSUE THREAD

**Issue by luigi-asprino** [rdfhdt/hdt-java#93] opened 2019-05-17 14:36 UTC
Hi,

I've downloaded DBpedia English [1,2] and I'm trying to read the dataset with the following code 

```
	private static void selectEntities(String entityFile, String dump) throws IOException {
		FileOutputStream fos = new FileOutputStream(new File(entityFile));
		HDT hdt = HDTManager.mapIndexedHDT(dump, null);
		try {
			IteratorTripleString it = hdt.search("", "http://dbpedia.org/ontology/wikiPageID", "");
			while (it.hasNext()) {
				TripleString tripleString = (TripleString) it.next();
				fos.write((tripleString.getSubject() + "\n").getBytes());
			}
		} catch (org.rdfhdt.hdt.exceptions.NotFoundException e) {
			logger.error(e.getMessage());
		}
		fos.flush();
		fos.close();
	}
```

I get this exeception
```
Exception in thread "main" java.lang.IllegalArgumentException: Size exceeds 
Integer.MAX_VALUE
	at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:869)
	at org.rdfhdt.hdt.dictionary.impl.section.PFCDictionarySectionMap.<init>(PFCDictionarySectionMap.java:137)
	at org.rdfhdt.hdt.dictionary.impl.section.DictionarySectionFactory.loadFrom(DictionarySectionFactory.java:84)
	at org.rdfhdt.hdt.dictionary.impl.FourSectionDictionary.mapFromFile(FourSectionDictionary.java:134)
	at org.rdfhdt.hdt.hdt.impl.HDTImpl.mapFromHDT(HDTImpl.java:273)
	at org.rdfhdt.hdt.hdt.HDTManagerImpl.doMapIndexedHDT(HDTManagerImpl.java:65)
	at org.rdfhdt.hdt.hdt.HDTManager.mapIndexedHDT(HDTManager.java:148)
	at it.unibo.disi.fox.experiments.fdistinctions.InputDatasetCreator.selectEntities(InputDatasetCreator.java:59)
	at it.unibo.disi.fox.experiments.fdistinctions.InputDatasetCreator.createDatasetUsingDump(InputDatasetCreator.java:53)
	at it.unibo.disi.fox.experiments.fdistinctions.InputDatasetCreator.main(InputDatasetCreator.java:46)
```

Any idea?

[1] http://gaia.infor.uva.es/hdt/dbpedia2016-10/dbpedia2016-10.hdt
[2] http://gaia.infor.uva.es/hdt/dbpedia2016-10/dbpedia2016-10.hdt.index.v1-1

**Comment by mielvds** [comment] 2019-05-17 14:49
Tried https://github.com/rdfhdt/hdt-java/tree/long-dict-id?

**Comment by luigi-asprino** [comment] 2019-05-17 14:56
Yes
```
System.out.println(TripleID.size());
```
prints 48

**Comment by mielvds** [comment] 2019-12-10 15:31
is this still the case?

**Comment by luigi-asprino** [comment] 2019-12-10 16:09
Hi @mielvds 
I've checked out the master and added this dependency 

```
<dependency>
	<groupId>org.rdfhdt</groupId>
	<artifactId>hdt-java-core</artifactId>
	<version>2.1.1</version>
</dependency>
```
and now I get this error

```
Exception in thread "main" java.lang.IllegalArgumentException: Size exceeds Integer.MAX_VALUE
	at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:869)
	at org.rdfhdt.hdt.dictionary.impl.section.PFCDictionarySectionMap.<init>(PFCDictionarySectionMap.java:138)
	at org.rdfhdt.hdt.dictionary.impl.section.DictionarySectionFactory.loadFrom(DictionarySectionFactory.java:84)
	at org.rdfhdt.hdt.dictionary.impl.FourSectionDictionary.mapFromFile(FourSectionDictionary.java:134)
	at org.rdfhdt.hdt.hdt.impl.HDTImpl.mapFromHDT(HDTImpl.java:279)
	at org.rdfhdt.hdt.hdt.HDTManagerImpl.doMapIndexedHDT(HDTManagerImpl.java:66)
	at org.rdfhdt.hdt.hdt.HDTManager.mapIndexedHDT(HDTManager.java:148)
	at it.cnr.istc.stlab.App.selectEntities(App.java:24)
	at it.cnr.istc.stlab.App.main(App.java:45)
```

**Comment by afs** [comment] 2021-01-16 16:01
Another report: https://stackoverflow.com/questions/65728294/how-to-load-large-hdt-files-using-jena

In this StackOverflow report the line numbers align with Java11.

The 3rd argument to `FileChannelImpl.map` (the `size` parameter) is greater than `Integer.MAX_VALUE` (2G) which is mentioned in the javadoc, despite the argument to `map` being a long.

The javadoc for `PFCDictionarySectionBig` says it is written to work around this.

`DictionarySectionFactory` has two `loadFrom` operations. Only one has adapting code to call `PFCDictionarySectionBig` and the stacktrace provided at SO shows a call of the other method.

Is it possible to make HDT use `PFCDictionarySectionBig`?

**Comment by mielvds** [comment] 2021-01-18 09:12
This would need an implemention of the memorymapped section `PFCDictionarySectionMap`, thus probably `PFCDictionarySectionMapBig`. I'm not super familiar with the codebase, but I could take a crack at it if someone adds a test that reproduces the issue.

**Comment by afs** [comment] 2021-01-21 11:06
>a test that reproduces the issue.

I'm afraid I have not a test case for you. The original report on StackOverflow was about `dbpedia2016-10.hdt`. When I saw the report, the stacktrace was something I vaguely understood so I raised the issue here because it looked an HDT issue, not a user issue. I don't know the SO user at all.

**Comment by mielvds** [comment] 2021-04-16 07:31
Closing this because of #126

**Closed by mielvds** 2021-04-16 07:31 UTC
